def styleSheet(mainWindow):
     mainWindow.setStyleSheet("/*\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"Colour scheme used:\n"
"- White (text): #eff0f1\n"
"- Dark black (main bg): #272a2d\n"
"- Lighter dark black (menu bar): #373b3f\n"
"- Dark blue: #18465d\n"
"- Gray: #76797C\n"
"- Red (accents): #db1c49\n"
"\n"
"Useful reference on QSS:\n"
" - http://doc.qt.io/qt-5/stylesheet-reference.html#alternate-background-color-prop\n"
"\n"
"Be sure to change all image urls to the appropriate folder on your system.\n"
"*/\n"
"\n"
"/*================================================================\n"
"QWidget\n"
"================================================================*/\n"
"QWidget {\n"
"    color: #eff0f1;\n"
"    background-color: #272a2d;\n"
"    selection-background-color: #db1c49;\n"
"    selection-color: #eff0f1;\n"
"}\n"
"\n"
"QWidget::item:hover {\n"
"    background-color: #18465d;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QWidget::item:selected {\n"
"    background-color: #18465d;\n"
"}\n"
"\n"
"/*================================================================\n"
"QCheckBox/QGroupBox\n"
"================================================================*/\n"
"\n"
"QGroupBox::indicator:checked:hover,\n"
"QGroupBox::indicator:checked:focus,\n"
"QGroupBox::indicator:checked:pressed {\n"
"    border: none;\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/checkbox_checked_focus.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/checkbox_indeterminate.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:focus,\n"
"QCheckBox::indicator:indeterminate:hover,\n"
"QCheckBox::indicator:indeterminate:pressed {\n"
"    image: url(C:/Users/franc/AppData/Roaming/TeXstudio/rc/checkbox_indeterminate_focus.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled,\n"
"QGroupBox::indicator:checked:disabled {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/checkbox_checked_disabled.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:disabled,\n"
"QGroupBox::indicator:unchecked:disabled {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/checkbox_unchecked_disabled.png);\n"
"}\n"
"\n"
"/*================================================================\n"
"QMenuBar - e.g. Main toolbar (file/edit/idefix etc.)\n"
"================================================================*/\n"
"QMenuBar {\n"
"    color: #eff0f1;\n"
"    background-color: #373b3f;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/*================================================================\n"
"QMenu\n"
"================================================================*/\n"
"QMenu {\n"
"    border: 1px solid #76797C;\n"
"    color: #eff0f1;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 2px;\n"
"    background: #76797C;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"/*================================================================\n"
"QToolbar\n"
"================================================================*/\n"
"QToolBar {\n"
"    border: 1px solid #393838;\n"
"    background: 1px solid #272a2d;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/Hmovetoolbar.png);\n"
"}\n"
"\n"
"QToolBar::handle:vertical {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/Vmovetoolbar.png);\n"
"}\n"
"\n"
"QToolBar::separator:horizontal {\n"
"    width: 2px;\n"
"    margin: 3px 10px;\n"
"    background-color: #76797C;\n"
"}\n"
"\n"
"QToolBar::separator:vertical {\n"
"    height: 2px;\n"
"    margin: 10px 3px;\n"
"    background-color: #76797C;\n"
"}\n"
"\n"
"/*================================================================\n"
"QScrollBar - e.g. Scrollbar in internal PDFviewer, editor window etc.\n"
"================================================================*/\n"
"QScrollBar:horizontal {\n"
"    height: 25px;\n"
"    margin: 3px 27px 3px 27px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"    background-color: #000000;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #76797C;\n"
"    min-width: 15px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    margin: 0px 3px 0px 3px;\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/right_arrow_disabled.png);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    margin: 0px 3px 0px 3px;\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/left_arrow_disabled.png);\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover,\n"
"QScrollBar::add-line:horizontal:on {\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/right_arrow.png);\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover,\n"
"QScrollBar::sub-line:horizontal:on {\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/left_arrow.png);\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal,\n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: #000000;\n"
"    width: 25px;\n"
"    margin: 27px 3px 27px 3px;\n"
"    border: 1px solid #2A2929;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #76797C;\n"
"    min-height: 15px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    margin: 3px 0px 3px 0px;\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/up_arrow_disabled.png);\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    margin: 3px 0px 3px 0px;\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/down_arrow_disabled.png);\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover,\n"
"QScrollBar::sub-line:vertical:on {\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/up_arrow.png);\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover,\n"
"QScrollBar::add-line:vertical:on {\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/down_arrow.png);\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/*================================================================\n"
"QTabBar - e.g. File tabs (top), Bottom panel tabs (top), Autocompleter window tabs (bottom)\n"
"================================================================*/\n"
"QTabBar {\n"
"    qproperty-drawBase: 0; /* important */\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* <FIX> Workaround for QTabBars created from docked QDockWidgets which don\'t draw the border if not set and reseted as follows: */\n"
"QTabBar {\n"
"    border-top: 1px transparent #76797C;  /* set color for all QTabBars */\n"
"}\n"
"QDialog QTabBar {\n"
"    border-color: transparent; /* set color for QTabBars inside Preferences dialog */\n"
"}\n"
"/* </FIX> */\n"
"\n"
"QTabBar::close-button {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/close.png);\n"
"    background: transparent;\n"
"    margin-top: 6px;\n"
"    margin-bottom: 6px;\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/close-hover.png);\n"
"    background: transparent;\n"
"    margin-top: 6px;\n"
"    margin-bottom: 6px;\n"
"}\n"
"\n"
"QTabBar::close-button:pressed {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/close-pressed.png);\n"
"    background: transparent;\n"
"    margin-top: 6px;\n"
"    margin-bottom: 6px;\n"
"}\n"
"\n"
"/* TOP TABS */\n"
"\n"
"QTabBar::tab:top {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 1px transparent black;\n"
"    background-color: #31363b;\n"
"    padding: 5px;\n"
"    min-width: 50px;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    color: #eff0f1;\n"
"    background-color: #54575B;\n"
"    border: 2px solid #76797C;\n"
"    border-bottom: 3px solid #3daee9;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover {\n"
"    background-color: #18465d;\n"
"}\n"
"\n"
"/* BOTTOM TABS */\n"
"\n"
"QTabBar::tab:bottom {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-top: 1px transparent black;\n"
"    background-color: #31363b;\n"
"    padding: 5px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    min-width: 50px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    color: #eff0f1;\n"
"    background-color: #54575B;\n"
"    border: 2px solid #76797C;\n"
"    border-top: 3px solid #3daee9;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:hover {\n"
"    background-color: #18465d;\n"
"}\n"
"\n"
"/*================================================================\n"
"QDockWidget - e.g. \"Search\" header in internal PDF viewer \n"
"================================================================*/\n"
"QDockWidget {\n"
"    titlebar-close-icon: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/transparent.png);\n"
"    titlebar-normal-icon: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/transparent.png);\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"    background: #373b3f; \n"
"    color: transparent;\n"
"    border: 1px transparent;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QDockWidget::close-button,\n"
"QDockWidget::float-button {\n"
"    border: transparent;\n"
"    padding: 0px;\n"
"    icon-size: 25px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QDockWidget::float-button {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/undock.png);\n"
"    subcontrol-position: right center;\n"
"    left: -50px;\n"
"}\n"
"\n"
"QDockWidget::close-button {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/close.png);\n"
"    subcontrol-position: right center;\n"
"    left: -10px;\n"
"}\n"
"\n"
"QDockWidget::float-button:hover {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/undock-pressed.png);\n"
"    subcontrol-position: right center;\n"
"    left: -50px;\n"
"}\n"
"\n"
"QDockWidget::close-button:hover {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/close-pressed.png);\n"
"    subcontrol-position: right center;\n"
"    left: -10px;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed {\n"
"    padding: 2px -2px -2px 2px;\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/close-pressed.png);\n"
"}\n"
"\n"
"QDockWidget::float-button:pressed {\n"
"    padding: 2px -2px -2px 2px;\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/undock-pressed.png);\n"
"}\n"
"\n"
"QDockWidget QListView {\n"
"    outline: 0;\n"
"    background: #272a2d;\n"
"    alternate-background-color: #373b3f;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"/*================================================================\n"
"QTreeView, QListView\n"
"================================================================*/\n"
"QTreeView,\n"
"QListView {\n"
"    border: 1px solid #76797C;\n"
"    background-color: #232629;\n"
"}\n"
"\n"
"QTreeView:branch:selected,\n"
"QTreeView:branch:hover {\n"
"    background: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"    border-image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/branch_closed.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/branch_open.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed:hover,\n"
"QTreeView::branch:closed:has-children:has-siblings:hover {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/branch_closed-on.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings:hover,\n"
"QTreeView::branch:open:has-children:has-siblings:hover {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/branch_open-on.png);\n"
"}\n"
"\n"
"QListView::item:!selected:hover,\n"
"QTreeView::item:!selected:hover {\n"
"    background: #18465d;\n"
"    outline: 0;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QListView::item:selected:hover,\n"
"QTreeView::item:selected:hover {\n"
"    background: #287399;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QTreeView::indicator:checked,\n"
"QListView::indicator:checked {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/checkbox_checked.png);\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked,\n"
"QListView::indicator:unchecked {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/checkbox_unchecked.png);\n"
"}\n"
"\n"
"QTreeView::indicator:checked:hover,\n"
"QTreeView::indicator:checked:focus,\n"
"QTreeView::indicator:checked:pressed,\n"
"QListView::indicator:checked:hover,\n"
"QListView::indicator:checked:focus,\n"
"QListView::indicator:checked:pressed {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/checkbox_checked_focus.png);\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked:hover,\n"
"QTreeView::indicator:unchecked:focus,\n"
"QTreeView::indicator:unchecked:pressed,\n"
"QListView::indicator:unchecked:hover,\n"
"QListView::indicator:unchecked:focus,\n"
"QListView::indicator:unchecked:pressed {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/checkbox_unchecked_focus.png);\n"
"}\n"
"\n"
"/*================================================================\n"
"QPushButton\n"
"================================================================*/\n"
"QPushButton {\n"
"    color: #eff0f1;\n"
"    background-color: #31363b;\n"
"    border-width: 1px;\n"
"    border-color: #76797C;\n"
"    border-style: solid;\n"
"    padding: 5px;\n"
"    border-radius: 2px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #31363b;\n"
"    border-width: 1px;\n"
"    border-color: #454545;\n"
"    border-style: solid;\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 2px;\n"
"    color: #454545;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"    background-color: #18465d;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #18465d;\n"
"    padding-top: -15px;\n"
"    padding-bottom: -17px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #76797C;\n"
"    border-color: #6A6969;\n"
"}\n"
"\n"
"/*================================================================\n"
"QToolButton - e.g. Reset pushbutton in GUI scaling, toolbar buttons\n"
"================================================================*/\n"
"QToolButton {\n"
"    text-align: center;\n"
"}\n"
"\n"
"/*================================================================\n"
"QComboBox\n"
"================================================================*/\n"
"QComboBox {\n"
"    selection-background-color: #db1c49;\n"
"    border: 1px solid #76797C;\n"
"    border-radius: 2px;\n"
"    padding: 5px;\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QComboBox:hover,\n"
"QPushButton:hover,\n"
"QAbstractSpinBox:hover,\n"
"QLineEdit:hover,\n"
"QTextEdit:hover,\n"
"QPlainTextEdit:hover,\n"
"QAbstractView:hover,\n"
"QTreeView:hover {\n"
"    border: 1px solid #3daee9;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #4a4a4a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #232629;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #76797C;\n"
"    selection-background-color: #18465d;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 35px;\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/down_arrow_disabled.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus {\n"
"    image: url(C:/Users/user/AppData/Roaming/TeXstudio/rc/down_arrow.png);\n"
"}\n"
"\n"
"/*================================================================\n"
"QLineEdit - e.g. Search textbox in internal pdf viewer\n"
"================================================================*/\n"
"QLineEdit {\n"
"    selection-background-color: #db1c49;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"/*================================================================\n"
"QHeaderView\n"
"================================================================*/\n"
"QHeaderView {\n"
"    background-color: #31363b;\n"
"    border: 1px transparent;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #31363b;\n"
"    color: #eff0f1;\n"
"    padding: 5px;\n"
"    border: 1px solid #76797C;\n"
"    border-radius: 0px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one {\n"
"    border-top: 1px solid #76797C;\n"
"}\n"
"\n"
"QHeaderView::section::vertical {\n"
"    border-top: transparent;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one {\n"
"    border-left: 1px solid #76797C;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal {\n"
"    border-left: transparent;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    color: #ffffff;\n"
"    background-color: #31363B;\n"
"}\n"
"\n"
"/*================================================================\n"
"QTableWidget\n"
"================================================================*/\n"
"QTableWidget {\n"
"    background-color: #373b3f; /*#232629;*/\n"
"    gridline-color: yellow; /*#31363b;*/\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    outline-style: none;\n"
"    color: #eff0f1;\n"
"    background: #31363b;\n"
"    border: none;\n"
"    border-bottom: 1px solid #31363b;\n"
"}\n"
"\n"
"/*================================================================\n"
"QTableView - e.g. configMenu()->Syntax highlighting table\n"
"================================================================*/\n"
"QTableView {\n"
"    border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}\n"
"\n"
"QTableView,\n"
"QHeaderView {\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QTableView::item:hover {\n"
"    background: #18465d;\n"
"}\n"
"\n"
"QTableView::item:pressed,\n"
"QListView::item:pressed,\n"
"QTreeView::item:pressed {\n"
"    background: #18465d;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QTableView::item:selected:active,\n"
"QTreeView::item:selected:active,\n"
"QListView::item:selected:active {\n"
"    background: #287399;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #31363b;\n"
"    border: 1px transparent #76797C;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"/*================================================================\n"
"QDialog - e.g. config menu, About TXS window, Wizards\n"
"================================================================*/\n"
"QDialog {\n"
"    background-color: #373b3f;\n"
"}\n"
"\n"
"QDialog QCheckBox,\n"
"QDialog QLabel {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QDialog QToolButton { /*Same as QPushButton*/\n"
"    color: #eff0f1;\n"
"    background-color: #31363b;\n"
"    border-width: 1px;\n"
"    border-color: #76797C;\n"
"    border-style: solid;\n"
"    padding: 5px;\n"
"    border-radius: 2px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QDialog QToolButton:hover,\n"
"QDialog QToolButton:focus { /*Same as QPushButton*/\n"
"    background-color: #18465d;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QDialog QToolButton:pressed { /*Same as QPushButton*/\n"
"    background-color: #18465d;\n"
"    padding-top: -15px;\n"
"    padding-bottom: -17px;\n"
"}\n"
"\n"
"/* <FIX> Specific to table in \"configMenu->Syntax highlighting\" (hopefully) */\n"
"\n"
"QDialog QTableWidget::item,\n"
"QDialog QTableView::item:hover { /* Turn off hover colour for cells -- it\'s distracting */\n"
"    background-color: #31363b;\n"
"}\n"
"\n"
"/* </FIX> */\n"
"\n"
"/*================================================================\n"
"QSlider - e.g. GUI scaling settings\n"
"================================================================*/\n"
"QSlider,\n"
"QSlider:active,\n"
"QSlider:!active {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 12px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    width: 12px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal,\n"
"QSlider::handle:vertical {\n"
"    background-color: #db1c49;\n"
"    border: 1px solid #db1c49;\n"
"    width: 10px;\n"
"    height: 15px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover,\n"
"QSlider::handle:vertical:hover,\n"
"QSlider::handle:horizontal:pressed,\n"
"QSlider::handle:vertical:pressed {\n"
"    border: 1px solid #A21538;\n"
"    background-color: #A21538;\n"
"}\n"
"\n"
"/*================================================================\n"
"QToolTip - e.g. popup upon hovering on filename tabs\n"
"================================================================*/\n"
"QToolTip {\n"
"    border: 1px solid #272a2d;\n"
"    background-color: #373b3f;\n"
"    color: white;\n"
"    padding: 0px;                /*remove padding, for fix combobox tooltip.*/\n"
"}\n"
"\n"
"/*================================================================\n"
"END\n"
"================================================================*/")